# -*- coding: utf-8 -*-
"""standardizing-merged-weather-outages-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozKWSuKvbS22ryTglITTnhvfjEHercQw
"""

import os
import pandas as pd
import numpy as np

filename = os.path.join(os.getcwd(), 'merged_weather_outages_2019_2024_outlier_cleaned.csv')
df = pd.read_csv(filename)

df.head()

num_cols = df.select_dtypes(include = np.number).columns
num_df = df[num_cols].copy()
print(num_cols)
num_cols.size

# drop potential labels, irrelevant/redundant cols, etc
num_df.drop(columns = ['pct_out_area_covered', 'pct_out_area_unified', 'pct_out_max_unified', 'pct_out_area', 'pct_out_max', 'fips_code', 'year'], inplace = True)
num_df.head()
print(num_df.columns.size)

# drop cols with binary/constant values
for i in num_df.columns:
  if num_df[i].unique().size <= 2:
    print(i + ": ")
    print(num_df[i].unique())
    num_df.drop(columns = [i], inplace = True)

print(num_df.columns)
print(num_df.columns.size)
num_df.head()

# standardize = mean of 0 and standard dev of 1
stan_num_df = num_df.copy()
for i in stan_num_df.columns:
  stan_num_df[i] = (stan_num_df[i] - stan_num_df[i].mean()) / stan_num_df[i].std()
stan_num_df.head()

# add back removed columns
stan_df = df.copy()
stan_df[num_df.columns] = stan_num_df
print(stan_df.columns == df.columns)
stan_df.head()

stan_df.to_csv('merged_weather_outages_2019_2024_standardized.csv')

